[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
src = ["src"]
packages = ["src/sqp_quantum"]

[project]
name = "sqp-quantum"
version = "1.0.4"
authors = [
  { name="Waldemar Renato Batista", email="wrenato91@gmail.com" },
]
description = "Simple quantum circuit simulator package"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
	"torch",
	"numpy",
]

[project.urls]
Homepage = "https://github.com/walderdob/SimpleQuantumPython/"
Issues = "https://github.com/walderdob/SimpleQuantumPython/issues"